# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eureka-server-ecalderc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_afd68929917f41d1a5e20fd76bde37b0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e5ca4f84a499411889d4fd2228bc0d77 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_afd68929917f41d1a5e20fd76bde37b0 }}/eureka-server:${{ github.sha }}
        file: /.github/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eureka-server-ecalderc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a3be336c0e2f4caebec4749b173312db }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_afd68929917f41d1a5e20fd76bde37b0 }}/eureka-server:${{ github.sha }}'